// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqOO8ojccTi1D5KGf28buD-fgJNUbpj8',
    appId: '1:545170534948:web:3357e04c3e7a98c7941eb1',
    messagingSenderId: '545170534948',
    projectId: 'smart-inventory-app-24289',
    authDomain: 'smart-inventory-app-24289.firebaseapp.com',
    storageBucket: 'smart-inventory-app-24289.firebasestorage.app',
    measurementId: 'G-F0TJMNBMQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3eudiHbc-IeP3Lz6safd2Ecs3X0ajvnY',
    appId: '1:545170534948:android:c12c1f8f9a51fee6941eb1',
    messagingSenderId: '545170534948',
    projectId: 'smart-inventory-app-24289',
    storageBucket: 'smart-inventory-app-24289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_f6AucidkSG3SWJcqLLl_f7KKsAR3AQ',
    appId: '1:545170534948:ios:c479cc80ebf809b2941eb1',
    messagingSenderId: '545170534948',
    projectId: 'smart-inventory-app-24289',
    storageBucket: 'smart-inventory-app-24289.firebasestorage.app',
    iosBundleId: 'com.example.smartinventoryapp.smartInventoryApp',
  );
}
